REM /UPS_PROD/sny_scripts/yesterdays_returns.sql
REM how to run this: 
REM move to the directory containing the script then enter this command: 
REM seneca-16(1) UPS50-UPS_PROD>>sqlplus -s [username]/[password] @yesterdays_returns.sql
SET ECHO off NEWP 0 SPA 0 LONG 8000 PAGES 0 FEED off HEAD off TRIMS on LINESIZE 1000
SET ESCAPE '\'
SPOOL /app/exlibris/aleph/prod/ups/alephe/apache/htdocs/yesterdays_returns.xml
SELECT '<?xml version="1.0" encoding="UTF-8"?>' FROM dual;
REM SELECT '<?xml-stylesheet type="text/xsl" href="yesterdays_returns.xsl"?>' FROM dual;
REM SELECT '<!-- this file generated by /sny_scripts/yesterdays_returns.sql -->' FROM dual;
SELECT '<document>' FROM dual;
SELECT 
'<item>'||chr(13)||chr(10)||
'<z13-open-date><![CDATA['||TRIM(UPS01.Z13.Z13_OPEN_DATE)||']]></z13-open-date>'||chr(13)||chr(10)|| 
'<z13-rec-key><![CDATA['||TRIM(UPS01.Z13.Z13_REC_KEY)||']]></z13-rec-key>'||chr(13)||chr(10)|| 
'<z13-author><![CDATA['||TRIM(UPS01.Z13.Z13_AUTHOR)||']]></z13-author>'||chr(13)||chr(10)|| 
'<z13-title><![CDATA['||TRIM(UPS01.Z13.Z13_TITLE)||']]></z13-title>'||chr(13)||chr(10)|| 
'<z13-year><![CDATA['||TRIM(UPS01.Z13.Z13_YEAR)||']]></z13-year>'||chr(13)||chr(10)|| 
'<z13-imprint><![CDATA['||TRIM(UPS01.Z13.Z13_IMPRINT)||']]></z13-imprint>'||chr(13)||chr(10)|| 
'<z13-isbn-issn><![CDATA['||TRIM(UPS01.Z13.Z13_ISBN_ISSN)||']]></z13-isbn-issn>'||chr(13)||chr(10)|| 
'<z30-rec-key><![CDATA['||TRIM(UPS01.Z30.Z30_REC_KEY)||']]></z30-rec-key>'||chr(13)||chr(10)|| 
'<z30-hol-doc-number-x><![CDATA['||TRIM(UPS01.Z30.Z30_HOL_DOC_NUMBER_X)||']]></z30-hol-doc-number-x>'||chr(13)||chr(10)|| 
'<z30-barcode><![CDATA['||TRIM(UPS01.Z30.Z30_BARCODE)||']]></z30-barcode>'||chr(13)||chr(10)|| 
'<z30-material><![CDATA['||TRIM(UPS01.Z30.Z30_MATERIAL)||']]></z30-material>'||chr(13)||chr(10)|| 
'<z30-collection><![CDATA['||TRIM(UPS01.Z30.Z30_COLLECTION)||']]></z30-collection>'||chr(13)||chr(10)|| 
'<z30-call-no><![CDATA['||TRIM(REPLACE(REPLACE(UPS01.Z30.Z30_CALL_NO,'$$h'),'$$i'))||']]></z30-call-no>'||chr(13)||chr(10)|| 
'<z30-date-last-return><![CDATA['||TRIM(UPS01.Z30.Z30_DATE_LAST_RETURN)||']]></z30-date-last-return>'||chr(13)||chr(10)|| 
'<z30-no-loans><![CDATA['||TRIM(UPS01.Z30.Z30_NO_LOANS)||']]></z30-no-loans>'||chr(13)||chr(10)||
'\<\/item\>'  
FROM BCC01.Z13 
LEFT JOIN UPS01.Z30 
ON BCC01.Z13.Z13_REC_KEY = substr(UPS01.Z30.Z30_REC_KEY,1,9) 
WHERE UPS01.Z30.Z30_DATE_LAST_RETURN LIKE TO_CHAR((sysdate-1),'YYYYMMDD') AND UPS01.Z30.Z30_COLLECTION LIKE '%CIRC%' 
ORDER BY UPS01.Z30.Z30_NO_LOANS DESC, BCC01.Z13.Z13_YEAR DESC, BCC01.Z13.Z13_TITLE;
SELECT '\<\/document\>' FROM dual;
SPOOL off
EXIT
